version: '3.8'

services:
  api:
    build: .
    container_name: url_shortener_api
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://localhost:3000
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=url_shortener
    depends_on:
      - postgres_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres_db:
    image: postgres:15-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
